### ISSUE TITLE
NPE in DependencyExtraction.ExtractDependenciesByMemberRefTraverser

### ISSUE THREAD

**Issue by mauhiz** [lihaoyi/acyclic#6]
Hi, this is my first try with this plugin and here is what I get :

```
java.lang.NullPointerException
        at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1$$anonfun$1.isDefinedAt(DependencyExtraction.scala:56)
        at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1$$anonfun$1.isDefinedAt(DependencyExtraction.scala:55)
        at acyclic.plugin.DependencyExtraction$CollectTypeTraverser$1.traverse(DependencyExtraction.scala:12)
        at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:58)
        at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:27)
        at scala.reflect.api.Trees$Traverser.traverseTypeAscription(Trees.scala:2478)
        at scala.reflect.internal.Trees$$anonfun$traverseMemberDef$1$1.apply$mcV$sp(Trees.scala:1214)
        at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
        at scala.reflect.internal.Trees$class.traverseMemberDef$1(Trees.scala:1203)
        at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1328)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
        at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:65)
        at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:27)
        at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2484)
        at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:62)
        at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:27)
        at scala.reflect.internal.Trees$$anonfun$traverseMemberDef$1$1.apply$mcV$sp(Trees.scala:1208)
        at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
        at scala.reflect.internal.Trees$class.traverseMemberDef$1(Trees.scala:1203)
        at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1327)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
        at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:65)
        at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:27)
        at scala.reflect.api.Trees$Traverser$$anonfun$traverseStats$1$$anonfun$apply$1.apply$mcV$sp(Trees.scala:2498)
        at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
        at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2497)
        at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1326)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
        at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:65)
        at acyclic.plugin.DependencyExtraction$.byMembers$1(DependencyExtraction.scala:71)
        at acyclic.plugin.DependencyExtraction$.apply(DependencyExtraction.scala:95)
        at acyclic.plugin.PluginPhase$$anon$1$$anonfun$6.apply(PluginPhase.scala:73)
        at acyclic.plugin.PluginPhase$$anon$1$$anonfun$6.apply(PluginPhase.scala:71)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1222)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1212)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1222)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1212)
        at scala.collection.immutable.Stream.foreach(Stream.scala:595)
        at scala.collection.TraversableOnce$class.toMap(TraversableOnce.scala:301)
        at scala.collection.AbstractTraversable.toMap(Traversable.scala:104)
        at acyclic.plugin.PluginPhase$$anon$1.run(PluginPhase.scala:89)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1500)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1487)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1580)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
        at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
        at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:97)
        at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:97)
        at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:97)
        at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:162)
        at sbt.compiler.AggressiveCompile$$anonfun$3.compileScala$1(AggressiveCompile.scala:96)
        at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:139)
        at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:86)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:38)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:36)
        at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:39)
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:38)
        at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:66)
        at sbt.inc.Incremental$.compile(Incremental.scala:38)
        at sbt.inc.IncrementalCompile$.apply(Compile.scala:26)
        at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:153)
        at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
        at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45)
        at sbt.Compiler$.apply(Compiler.scala:74)
        at sbt.Compiler$.apply(Compiler.scala:65)
        at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:789)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:781)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:781)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
```

My project is a Play 2.3.7 project with a few sub-projects; its environment is :
- Scala 2.11.5
- Java 8
- SBT 0.13.7 with cached resolution enabled

**Comment by lihaoyi** [comment]
Looks like one problem which causes this is Java sources, which don't generate Scala ASTs/sources. I'd guess Play uses/generates these as part of the project

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/lihaoyi/acyclic/pull/9
