### ISSUE TITLE
hooking acyclic into my project crashes

### ISSUE THREAD

**Issue by matanster** [lihaoyi/acyclic#8]
Hooking acyclic into my project crashes. Maybe I'm not using compatible versions of scala or something. Looking forward to using it after this is hopefully figured out!

### SBT about (before adding acyclic)
```
[info] This is sbt 0.13.6
[info] The current project is built against Scala 2.11.6
[info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, play.twirl.sbt.SbtTwirl, play.Play, play.PlayJava, play.PlayScala, com.typesafe.sbt.jse.SbtJsEngine, com.typesafe.sbt.jse.SbtJsTask, com.typesafe.sbt.web.SbtWeb, com.typesafe.sbt.webdriver.SbtWebDriver, com.typesafe.sbt.coffeescript.SbtCoffeeScript, com.typesafe.sbt.less.SbtLess, com.typesafe.sbt.jshint.SbtJSHint, com.typesafe.sbt.rjs.SbtRjs, com.typesafe.sbt.digest.SbtDigest, com.typesafe.sbt.mocha.SbtMocha, com.typesafe.sbt.gzip.SbtGzip, com.jamesward.play.BrowserNotifierPlugin, com.typesafe.sbteclipse.plugin.EclipsePlugin, com.typesafe.sbt.SbtStartScript, org.netbeans.nbsbt.plugin.NetBeansPlugin, com.typesafe.sbt.SbtScalariform, org.sbtidea.SbtIdeaPlugin, com.typesafe.sbt.SbtNativePackager
[info] sbt, sbt plugins, and build definitions are using Scala 2.10.4
```

### Stack trace:
```
$ last compile:compile
[debug] 
[debug] Initial source changes: 
[debug] 	removed:Set()
[debug] 	added: .....
[debug] Recompiling all 78 sources: invalidated sources (78) exceeded 50.0% of all sources
[info] Compiling 77 Scala sources and 1 Java source to .....
[debug] Getting compiler-interface from component compiler for Scala 2.11.6
[debug] Getting compiler-interface from component compiler for Scala 2.11.6
[debug] Running cached compiler 5d06c36f, interfacing (CompilerInterface) with Scala compiler version 2.11.6
[debug] Calling Scala compiler with arguments  (CompilerInterface):
[debug] 	-unchecked
[debug] 	-deprecation
[debug] 	-encoding
[debug] 	utf8
[debug] 	-unchecked
[debug] 	-feature
[debug] 	-feature
[debug] 	-language:reflectiveCalls
[debug] 	-Xplugin:/home/matan/.ivy2/cache/com.lihaoyi/acyclic_2.11/jars/acyclic_2.11-0.1.2.jar
[debug] 	-bootclasspath
[debug] 	/usr/lib/jvm/java-7-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-7-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-7-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-7-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-7-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-7-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-7-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-7-oracle/jre/classes:/home/matan/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar
[debug] 	-classpath
3.0.0-RC2.jar:/home/matan/.ivy2/cache/com.lihaoyi/acyclic_2.11/jars/acyclic_2.11-0.1.2.jar
java.lang.NullPointerException
	at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1$$anonfun$1.isDefinedAt(DependencyExtraction.scala:56)
	at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1$$anonfun$1.isDefinedAt(DependencyExtraction.scala:55)
	at acyclic.plugin.DependencyExtraction$CollectTypeTraverser$1.traverse(DependencyExtraction.scala:12)
	at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:58)
	at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:27)
	at scala.reflect.api.Trees$Traverser.traverseTypeAscription(Trees.scala:2478)
	at scala.reflect.internal.Trees$$anonfun$traverseMemberDef$1$1.apply$mcV$sp(Trees.scala:1214)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
	at scala.reflect.internal.Trees$class.traverseMemberDef$1(Trees.scala:1203)
	at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1328)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
	at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:65)
	at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:27)
	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2484)
	at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:62)
	at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:27)
	at scala.reflect.internal.Trees$$anonfun$traverseMemberDef$1$1.apply$mcV$sp(Trees.scala:1208)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
	at scala.reflect.internal.Trees$class.traverseMemberDef$1(Trees.scala:1203)
	at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1327)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
	at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:65)
	at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:27)
	at scala.reflect.api.Trees$Traverser$$anonfun$traverseStats$1$$anonfun$apply$1.apply$mcV$sp(Trees.scala:2498)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
	at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2497)
	at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1326)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
	at acyclic.plugin.DependencyExtraction$ExtractDependenciesByMemberRefTraverser$1.traverse(DependencyExtraction.scala:65)
	at acyclic.plugin.DependencyExtraction$.byMembers$1(DependencyExtraction.scala:71)
	at acyclic.plugin.DependencyExtraction$.apply(DependencyExtraction.scala:95)
	at acyclic.plugin.PluginPhase$$anon$1$$anonfun$6.apply(PluginPhase.scala:73)
	at acyclic.plugin.PluginPhase$$anon$1$$anonfun$6.apply(PluginPhase.scala:71)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1222)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1212)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1222)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1212)
	at scala.collection.immutable.Stream.foreach(Stream.scala:595)
	at scala.collection.TraversableOnce$class.toMap(TraversableOnce.scala:301)
	at scala.collection.AbstractTraversable.toMap(Traversable.scala:104)
	at acyclic.plugin.PluginPhase$$anon$1.run(PluginPhase.scala:89)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1500)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1487)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1580)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:97)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:97)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:97)
	at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:162)
	at sbt.compiler.AggressiveCompile$$anonfun$3.compileScala$1(AggressiveCompile.scala:96)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:139)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:86)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:38)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:36)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:39)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:38)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:66)
	at sbt.inc.Incremental$.compile(Incremental.scala:38)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:26)
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:153)
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
	at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45)
	at sbt.Compiler$.apply(Compiler.scala:74)
	at sbt.Compiler$.apply(Compiler.scala:65)
	at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:777)
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:769)
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:769)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (compile:compile) java.lang.NullPointerException
```

What might it be?

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/lihaoyi/acyclic/pull/9
